---
- name: send email example
  hosts: 192.168.1.20
  gather_facts: no
  tasks:
    - name: Send an email
      mail:
        host: smtp.hostinger.com
        port: 587
        username: email@itpanther.com
        password: StrongP@ssword001
        to: vijha1989@mailinator.com
        subject: "new code deployed"
        body: "new code deployed successfully"
        from: email@itpanther.com
        timeout: 20
